### ISSUE TITLE
where is the db file saved to?

### ISSUE THREAD

**Issue by saintnever** [vedipen/WifiRssiPlot#1]
I'm trying to use the database file for further analysis, but I cannot find where it is. Can you share it's default location? Thanks

**Comment by vedipen** [comment]
I am not storing the database in an explicit file. Rather I am using [SQLite Database](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html)'s default operation to store it. The database file will get generated in the memory when the app runs on the device.

It is there. One can't access it in an Android device is because that folder is private and cannot be seen using conventional methods, the OS protects that folder and that folder (and its contents e.g. database) can only be used by that certain application.

If you want to see it, run an emulator, run this application there, go to DDMS view, go to `/data/data/wifiRSSI/databases` and it's there. If you don't have access to DDMS, use this ADB Shell command: `$ adb pull /data/data/wifiRSSI/databases/db123#4.db`

A better way is to use [this vector](https://github.com/vedipen/WifiRssiPlot/blob/8b756c79296d3efb5e440c76f63453a764762557/WifiSignalStrengthRSSI/app/src/main/java/com/example/vedipen/wifiRSSI/MainActivity.java#L59) RSSIDetails itself for your analysis or write this vector in an explicit file located in a public location, say in `root/WifiRSSI`. You can always use sql queries to get the same from the database.

Regards,
Dipen

**Comment by saintnever** [comment]
I see. Thanks！

**Comment by vedipen** [comment]
Your welcome xD
